/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tickets/update/{ticketPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Atualizar ticket
         * @description Atualiza um ticket existente. Apenas os campos enviados serão alterados. Todas as mudanças são registradas automaticamente no log de auditoria (TicketLog).
         */
        put: operations["updateTicket"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worklog/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar novo usuário
         * @description Cria um novo usuário com a role padrão USER. Requer autenticação como ADMIN. O email deve ser único no sistema.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worklog/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar access token
         * @description Gera um novo access token e um novo refresh token a partir do cookie `worklog_refresh`. O refresh token anterior é invalidado e os cookies são re-emitidos.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worklog/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar logout
         * @description Invalida o refresh token (se presente) no Redis e expira os cookies de auth.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worklog/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar login
         * @description Autentica o usuário e emite os tokens via cookies `worklog_access` (path `/`) e `worklog_refresh` (path `/worklog/auth`). Ambos são HttpOnly e SameSite=Strict.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{publicId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desativar usuário
         * @description Desativa um usuário (soft delete). Requer role ADMIN.
         */
        post: operations["deactiveUserByPublicId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alterar a própria senha
         * @description Altera a senha do usuário autenticado e revoga TODAS as sessões ativas (refresh tokens) do usuário. Após o sucesso, o cliente deve fazer login novamente.
         */
        post: operations["changeMyPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar ticket
         * @description Cria um novo ticket de suporte. O cliente e o sistema devem estar ativos. O usuário responsável é opcional.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar sistema
         * @description Cria um novo sistema. O nome deve ser único.
         */
        post: operations["saveSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{publicId}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar filiais do cliente
         * @description Retorna as filiais do cliente, incluindo a matriz. Sem o parâmetro `status`
         *     devolve ativas e inativas, igual ao `GET /clients`.
         *     Funciona também para clientes desativados — só a criação exige cliente ativo.
         */
        get: operations["findBranchesByClient"];
        put?: never;
        /**
         * Cadastrar filial
         * @description Cadastra uma nova filial no cliente. O `documento` é obrigatório e precisa ter
         *     checksum válido para o tipo do **cliente persistido** (CPF para PF, CNPJ para PJ) —
         *     o tipo não é lido do corpo.
         *
         *     **Atenção ao status de erro:** documento com checksum inválido aqui responde
         *     **422**, enquanto o mesmo erro no `POST /clients` responde **400**. A diferença é
         *     intencional: no cadastro do cliente a validação é do Bean Validation (que conhece
         *     o `tipo` enviado no corpo) e aqui é regra de serviço (que só pode consultar o tipo
         *     já persistido).
         *
         *     Regras rejeitadas com 422: cliente inativo; cliente pessoa física (que tem apenas
         *     a matriz); `isMatriz: true` (promover uma filial a matriz é feito pelo `PATCH`);
         *     documento ausente; documento com checksum inválido.
         */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{publicId}/branches/{branchId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inativar filial
         * @description Inativa a filial (`enabled = false`). **Não é exclusão**: o registro permanece e
         *     continua aparecendo em `GET .../branches` sem filtro, ou com `status=INATIVO`.
         *
         *     **Consequência importante:** o `documento` da filial inativa **continua ocupando a
         *     unicidade global**. Recadastrar aquele CNPJ em outro cliente devolve 409 enquanto
         *     esta filial existir.
         *
         *     A **matriz não pode ser inativada** (422) — promova outra filial a matriz antes.
         *
         *     Requer perfil ADMIN.
         */
        post: operations["deactivateBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{publicId}/branches/{branchId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reativar filial
         * @description Reativa uma filial inativa (`enabled = true`). Contrapartida de
         *     `POST .../deactivate`.
         *
         *     **Idempotente:** reativar uma filial já ativa devolve 204 sem alterar nada.
         *
         *     **Não há risco de conflito de documento:** a filial inativa nunca liberou a
         *     unicidade global, então ninguém pôde ter tomado aquele documento no intervalo.
         *
         *     Rejeitado com 422: cliente inativo; cliente **pessoa física** que já tenha uma
         *     filial ativa (ele deve ter apenas a matriz).
         *
         *     Requer perfil ADMIN.
         */
        post: operations["activateBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar cliente
         * @description Cria um novo cliente associado a um ou mais sistemas. O nome deve ser único.
         */
        post: operations["saveClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar sistema por ID
         * @description Retorna um sistema específico pelo seu publicId (UUID).
         */
        get: operations["findSystemByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar sistema
         * @description Atualiza parcialmente um sistema. Apenas os campos enviados serão alterados (PATCH).
         */
        patch: operations["updateSystem"];
        trace?: never;
    };
    "/clients/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar cliente por ID
         * @description Retorna um cliente específico pelo seu publicId (UUID).
         */
        get: operations["findClientByPublicId"];
        put?: never;
        post?: never;
        /**
         * Excluir cliente (soft delete)
         * @description Marca o cliente como inativo (`isEnabled = false`). Restrito a ADMIN.
         */
        delete: operations["softDeleteClient"];
        options?: never;
        head?: never;
        /**
         * Atualizar cliente
         * @description Atualiza parcialmente um cliente. Apenas os campos enviados serão alterados (PATCH).
         */
        patch: operations["updateClient"];
        trace?: never;
    };
    "/clients/{publicId}/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar filial
         * @description Atualiza parcialmente uma filial. Apenas os campos enviados são alterados (PATCH).
         *
         *     **`contatos`**: ausente não altera nada; presente **substitui a lista inteira**.
         *
         *     **`isMatriz: true`** promove esta filial a matriz e rebaixa a anterior na mesma
         *     transação. **`isMatriz: false`** sobre a matriz atual é rejeitado com 422 — o
         *     cliente ficaria sem matriz; promova outra filial no lugar.
         *
         *     **`enabled` não existe aqui**: inativar filial tem endpoint próprio
         *     (`POST .../deactivate`).
         *
         *     Reenviar o **próprio** documento sem alterá-lo é aceito e não devolve 409.
         *
         *     Rejeitado com 422: cliente inativo; documento com checksum inválido para o tipo do
         *     cliente; rebaixar a matriz; promover uma filial inativa; mais de um contato
         *     marcado como `principal`.
         */
        patch: operations["updateBranch"];
        trace?: never;
    };
    "/users/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar usuário por ID
         * @description Retorna um usuário específico pelo seu publicId (UUID).
         */
        get: operations["findUserByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar usuário autenticado
         * @description Retorna os dados do usuário autenticado (a partir do token JWT).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos os usuários
         * @description Retorna todos os usuários cadastrados com suas roles.
         */
        get: operations["findAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tickets
         * @description Retorna uma página de tickets (resumo) com filtros opcionais por título, status, prioridade, cliente, sistema, usuário, faixa de datas de criação e visibilidade. O parâmetro `visibility` (ATIVO/INATIVO/TODOS) só é honrado para usuários ADMIN; usuários comuns sempre veem apenas tickets ativos.
         */
        get: operations["findAllTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar ticket por ID
         * @description Retorna um ticket específico pelo seu publicId (UUID), incluindo dados do cliente, sistema e usuário responsável.
         */
        get: operations["getTicketByPublicId"];
        put?: never;
        post?: never;
        /**
         * Soft-delete de ticket
         * @description Marca o ticket como inativo (`isEnabled = false`). Operação reservada para usuários ADMIN. O histórico de auditoria é preservado.
         */
        delete: operations["deleteTicket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{publicId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar logs de auditoria do ticket
         * @description Retorna uma página do histórico de alterações (TicketLog) do ticket informado, ordenada por data de alteração decrescente.
         */
        get: operations["getTicketLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos os sistemas
         * @description Retorna todos os sistemas cadastrados.
         */
        get: operations["findAllSystems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar clientes
         * @description Retorna todos os clientes com suporte a filtros por nome, status (ATIVO/INATIVO/TODOS) e sistemas associados.
         */
        get: operations["findAllClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar CNPJ na Receita Federal
         * @description Consulta o CNPJ na CNPJá e devolve os dados já no formato do formulário de
         *     cadastro, prontos para o `POST /clients`. **Nada é persistido**: o usuário
         *     revisa e corrige antes de salvar.
         *
         *     O documento é validado localmente antes da consulta — CNPJ com checksum
         *     inválido devolve 400 sem gastar requisição no provedor, que limita a
         *     5 consultas por minuto por endereço IP.
         *
         *     **A inscrição estadual volta sempre em branco** com o provedor público:
         *     verificado contra a API real, `open.cnpja.com` não devolve o bloco de
         *     inscrições. Segue preenchimento manual. (A seleção da IE da UF do
         *     endereço está implementada e passa a valer sozinha caso o backend seja
         *     apontado para a API comercial, que devolve o bloco.)
         *
         *     O regime tributário só é preenchido quando o provedor afirma: MEI ou
         *     Simples Nacional. Lucro Presumido e Lucro Real não existem no contrato e
         *     ficam a cargo do usuário.
         *
         *     `situacaoCadastral` e `situacaoAtiva` são o aviso da tela, não campos do
         *     cadastro: CNPJ suspenso, inapto ou baixado vem **preenchido do mesmo
         *     jeito**, com `situacaoAtiva: false`, e quem decide se cadastra é o
         *     atendente.
         *
         *     A inscrição municipal não existe no contrato do provedor e volta sempre
         *     em branco. Nenhum contato vem marcado como principal: quem escolhe é o
         *     usuário.
         *
         *     As respostas bem-sucedidas ficam em cache no Redis por 24h
         *     (`worklog.cnpja.cache-ttl`), então repetir a consulta do mesmo CNPJ não
         *     consome o limite do provedor. Erros nunca são cacheados.
         */
        get: operations["lookupByCnpj"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TicketUpdateRequest: {
            title?: string;
            description?: string;
            solution?: string;
            /** @enum {string} */
            status?: "PENDING" | "AWAITING_CUSTOMER" | "AWAITING_DEVELOPMENT" | "COMPLETED" | "CANCELLED";
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            userId?: string;
            /** @enum {string} */
            priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
        };
        ClientSummary: {
            /** Format: uuid */
            publicId?: string;
            name?: string;
            enabled?: boolean;
        };
        SystemResponse: {
            /** Format: uuid */
            publicId?: string;
            name?: string;
            enabled?: boolean;
        };
        TicketResponse: {
            /** Format: uuid */
            publicId?: string;
            title?: string;
            description?: string;
            solution?: string;
            /** @enum {string} */
            status?: "PENDING" | "AWAITING_CUSTOMER" | "AWAITING_DEVELOPMENT" | "COMPLETED" | "CANCELLED";
            /** @enum {string} */
            priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            client?: components["schemas"]["ClientSummary"];
            system?: components["schemas"]["SystemResponse"];
            user?: components["schemas"]["UserSummary"];
        };
        UserSummary: {
            /** Format: uuid */
            publicId?: string;
            name?: string;
            email?: string;
        };
        ApiExceptionResponse: {
            mediaType?: components["schemas"]["MediaType"];
            /** Format: date-time */
            timestamp?: string;
            /** Format: int32 */
            status?: number;
            error?: string;
            message?: string;
            path?: string;
            fieldErrors?: {
                [key: string]: string;
            };
        };
        MediaType: {
            type?: string;
            subtype?: string;
            parameters?: {
                [key: string]: string;
            };
            /** Format: double */
            qualityValue?: number;
            wildcardType?: boolean;
            wildcardSubtype?: boolean;
            subtypeSuffix?: string;
            /** @example UTF-8 */
            charset?: string;
            concrete?: boolean;
        };
        RegisterRequest: {
            name?: string;
            email?: string;
            password?: string;
        };
        RegisterResponse: {
            publicId?: string;
            name?: string;
            email?: string;
            createdAt?: string;
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        ChangePasswordRequest: {
            currentPassword?: string;
            newPassword?: string;
        };
        TicketRequest: {
            title?: string;
            description?: string;
            solution?: string;
            /** @enum {string} */
            status: "PENDING" | "AWAITING_CUSTOMER" | "AWAITING_DEVELOPMENT" | "COMPLETED" | "CANCELLED";
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            clientId: string;
            /** Format: uuid */
            systemId: string;
            /** Format: uuid */
            userId?: string;
            /** @enum {string} */
            priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
        };
        SystemRequest: {
            name?: string;
        };
        AddressRequest: {
            cep?: string;
            logradouro?: string;
            numero?: string;
            complemento?: string;
            bairro?: string;
            cidade?: string;
            uf?: string;
        };
        BranchRequest: {
            documento?: string;
            isMatriz?: boolean;
            apelido?: string;
            inscricaoEstadual?: string;
            inscricaoMunicipal?: string;
            address?: components["schemas"]["AddressRequest"];
            contatos?: components["schemas"]["ContactRequest"][];
        };
        ContactRequest: {
            /** @enum {string} */
            tipo: "EMAIL" | "TELEFONE" | "CELULAR" | "WHATSAPP";
            valor?: string;
            descricao?: string;
            principal?: boolean;
        };
        AddressResponse: {
            cep?: string;
            logradouro?: string;
            numero?: string;
            complemento?: string;
            bairro?: string;
            cidade?: string;
            uf?: string;
        };
        BranchResponse: {
            /** Format: uuid */
            publicId?: string;
            documento?: string;
            isMatriz?: boolean;
            apelido?: string;
            inscricaoEstadual?: string;
            inscricaoMunicipal?: string;
            address?: components["schemas"]["AddressResponse"];
            contatos?: components["schemas"]["ContactResponse"][];
            enabled?: boolean;
        };
        ContactResponse: {
            /** Format: uuid */
            publicId?: string;
            /** @enum {string} */
            tipo?: "EMAIL" | "TELEFONE" | "CELULAR" | "WHATSAPP";
            valor?: string;
            descricao?: string;
            principal?: boolean;
        };
        ClientRequest: {
            /** @enum {string} */
            tipo: "PJ" | "PF";
            name?: string;
            nomeFantasia?: string;
            /** @enum {string} */
            regimeTributario?: "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL" | "MEI" | "IMUNE" | "ISENTO";
            systemsPublicIds?: string[];
            branches?: components["schemas"]["BranchRequest"][];
            enabled?: boolean;
        };
        ClientResponse: {
            /** Format: uuid */
            publicId?: string;
            /** @enum {string} */
            tipo?: "PJ" | "PF";
            name?: string;
            nomeFantasia?: string;
            /** @enum {string} */
            regimeTributario?: "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL" | "MEI" | "IMUNE" | "ISENTO";
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            systems?: components["schemas"]["SystemResponse"][];
            branches?: components["schemas"]["BranchResponse"][];
        };
        ClientUpdateRequest: {
            /** @enum {string} */
            tipo?: "PJ" | "PF";
            name?: string;
            nomeFantasia?: string;
            /** @enum {string} */
            regimeTributario?: "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL" | "MEI" | "IMUNE" | "ISENTO";
            systemsPublicIds?: string[];
            enabled?: boolean;
        };
        BranchUpdateRequest: {
            documento?: string;
            isMatriz?: boolean;
            apelido?: string;
            inscricaoEstadual?: string;
            inscricaoMunicipal?: string;
            address?: components["schemas"]["AddressRequest"];
            contatos?: components["schemas"]["ContactRequest"][];
        };
        RoleResponse: {
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        UserResponse: {
            publicId?: string;
            email?: string;
            name?: string;
            roles?: components["schemas"]["RoleResponse"][];
            createdAt?: string;
        };
        TicketFiltersParams: {
            title?: string;
            /** @enum {string} */
            status?: "PENDING" | "AWAITING_CUSTOMER" | "AWAITING_DEVELOPMENT" | "COMPLETED" | "CANCELLED";
            /** @enum {string} */
            priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
            /** Format: uuid */
            clientId?: string;
            /** Format: uuid */
            systemId?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: date */
            createdFrom?: string;
            /** Format: date */
            createdTo?: string;
            /** @enum {string} */
            visibility?: "ATIVO" | "INATIVO" | "TODOS";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        TicketSummary: {
            /** Format: uuid */
            publicId?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "PENDING" | "AWAITING_CUSTOMER" | "AWAITING_DEVELOPMENT" | "COMPLETED" | "CANCELLED";
            /** @enum {string} */
            priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            client?: components["schemas"]["ClientSummary"];
            system?: components["schemas"]["SystemResponse"];
            user?: components["schemas"]["UserSummary"];
        };
        PageTicketSummary: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["TicketSummary"][];
            /** Format: int32 */
            number?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        TicketLogResponse: {
            /** Format: uuid */
            changeGroupId?: string;
            fieldChanged?: string;
            /** @enum {string} */
            fieldType?: "STRING" | "INTEGER" | "DECIMAL" | "BOOLEAN" | "DATETIME" | "ENTITY_REF";
            oldValue?: string;
            newValue?: string;
            /** Format: date-time */
            changeDate?: string;
            user?: components["schemas"]["UserSummary"];
        };
        PageTicketLogResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["TicketLogResponse"][];
            /** Format: int32 */
            number?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        ClientFiltersParams: {
            name?: string;
            /** @enum {string} */
            status?: "ATIVO" | "INATIVO" | "TODOS";
            systems?: string[];
            documento?: string;
            /** @enum {string} */
            tipo?: "PJ" | "PF";
        };
        CnpjLookupResponse: {
            /** @enum {string} */
            tipo?: "PJ" | "PF";
            name?: string;
            nomeFantasia?: string;
            /** @enum {string} */
            regimeTributario?: "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL" | "MEI" | "IMUNE" | "ISENTO";
            situacaoCadastral?: string;
            situacaoAtiva?: boolean;
            branches?: components["schemas"]["BranchRequest"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do ticket (UUID) */
                ticketPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdateRequest"];
            };
        };
        responses: {
            /** @description Ticket atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Ticket não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Usuário registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Acesso negado — requer role ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Email já cadastrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                worklog_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Token renovado com sucesso; novos cookies emitidos */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token cookie ausente, inválido ou expirado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                worklog_refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Logout realizado com sucesso; cookies expirados via Set-Cookie */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso; cookies emitidos via Set-Cookie */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactiveUserByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do usuário (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário desativado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — requer role ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Senha alterada com sucesso; todas as sessões revogadas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requisição inválida (campos obrigatórios ausentes ou inválidos) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Senha atual incorreta */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRequest"];
            };
        };
        responses: {
            /** @description Ticket criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Cliente, sistema ou usuário não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Cliente ou sistema inativo */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    saveSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemRequest"];
            };
        };
        responses: {
            /** @description Sistema criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Sistema com este nome já existe */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    findBranchesByClient: {
        parameters: {
            query?: {
                /** @description Filtro de status: ATIVO, INATIVO ou TODOS (padrão: TODOS) */
                status?: "ATIVO" | "INATIVO" | "TODOS";
            };
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de filiais retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"][];
                };
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequest"];
            };
        };
        responses: {
            /** @description Filial criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Documento já cadastrado em outra filial */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Regra de negócio violada */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    deactivateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
                /** @description ID público da filial (UUID) */
                branchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filial inativada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão (requer ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente ou filial não encontrada (inclui filial de outro cliente) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Tentativa de inativar a matriz, ou cliente inativo */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    activateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
                /** @description ID público da filial (UUID) */
                branchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filial reativada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão (requer ADMIN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente ou filial não encontrada (inclui filial de outro cliente) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Cliente inativo, ou pessoa física que já tem filial ativa */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    saveClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description Cliente criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Cliente com este nome já existe */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    findSystemByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do sistema (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sistema encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Sistema não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    updateSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do sistema (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemRequest"];
            };
        };
        responses: {
            /** @description Sistema atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Sistema não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    findClientByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    softDeleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente desativado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão (ADMIN obrigatório) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdateRequest"];
            };
        };
        responses: {
            /** @description Cliente atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Cliente não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do cliente (UUID) */
                publicId: string;
                /** @description ID público da filial (UUID) */
                branchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchUpdateRequest"];
            };
        };
        responses: {
            /** @description Filial atualizada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Dados de entrada inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Cliente ou filial não encontrada (inclui filial de outro cliente) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Documento já cadastrado em outra filial */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Regra de negócio violada */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    findUserByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do usuário (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Usuário não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    findAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuários retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    findAllTickets: {
        parameters: {
            query: {
                filters: components["schemas"]["TicketFiltersParams"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de tickets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketSummary"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTicketSummary"];
                };
            };
        };
    };
    getTicketByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do ticket (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Ticket não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID público do ticket (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket desativado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — requer role ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ticket não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    getTicketLogs: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                /** @description ID público do ticket (UUID) */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de logs do ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketLogResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTicketLogResponse"];
                };
            };
            /** @description Ticket não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
    findAllSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de sistemas retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemResponse"][];
                };
            };
        };
    };
    findAllClients: {
        parameters: {
            query: {
                filtersParams: components["schemas"]["ClientFiltersParams"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de clientes retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"][];
                };
            };
        };
    };
    lookupByCnpj: {
        parameters: {
            query: {
                /**
                 * @description CNPJ do estabelecimento, com ou sem máscara
                 * @example 07526557011659
                 */
                documento: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta realizada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CnpjLookupResponse"];
                };
            };
            /** @description CNPJ ausente ou inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CnpjLookupResponse"];
                };
            };
            /** @description CNPJ não registrado na Receita Federal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Limite de consultas do provedor atingido; tente novamente em instantes */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
            /** @description Provedor de consulta indisponível; preencha o cadastro manualmente */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiExceptionResponse"];
                };
            };
        };
    };
}
